"""empty message

Revision ID: 70356c5ba498
Revises: 
Create Date: 2020-04-08 20:18:28.534044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70356c5ba498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('country', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('desciption', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('movies', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('movies', 'typeofMovie',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('movies', 'year')
    op.drop_column('movies', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('description', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('movies', 'typeofMovie',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('movies', 'id')
    op.drop_column('movies', 'desciption')
    op.drop_column('movies', 'country')
    # ### end Alembic commands ###
